version: '3.8'
services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    container_name: api-blog
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    container_name: app-blog
